# Generated by Django 2.1.7 on 2019-03-06 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtitle', models.CharField(max_length=255)),
                ('eventlocation', models.CharField(max_length=255)),
                ('eventdate', models.DateField()),
                ('eventtime', models.TimeField()),
                ('eventdescription', models.TextField()),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winename', models.CharField(max_length=255)),
                ('wineyear', models.CharField(max_length=255)),
                ('wineprice', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'wine',
            },
        ),
        migrations.CreateModel(
            name='WineReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewtitle', models.CharField(max_length=255)),
                ('reviewdate', models.DateField()),
                ('reviewrating', models.SmallIntegerField()),
                ('reviewtext', models.TextField()),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wineapp.Wine')),
            ],
            options={
                'db_table': 'winereview',
            },
        ),
        migrations.CreateModel(
            name='Winery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wineryname', models.CharField(max_length=255)),
                ('winerylocation', models.CharField(max_length=255)),
                ('wineryurl', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'winery',
            },
        ),
        migrations.CreateModel(
            name='WineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=255)),
                ('typedescription', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'winetype',
            },
        ),
        migrations.AddField(
            model_name='wine',
            name='winery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wineapp.Winery'),
        ),
        migrations.AddField(
            model_name='wine',
            name='winetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wineapp.WineType'),
        ),
    ]
